steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/automerch:latest', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/automerch:latest']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'automerch'
      - '--image'
      - 'gcr.io/$PROJECT_ID/automerch:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '300'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'AUTOMERCH_DRY_RUN=false,ETSY_REDIRECT_URI=https://automerch-715156784717.us-central1.run.app/auth/etsy/callback,PRINTFUL_API_KEY=7IAG3tMfxJhxWb06c07ao5OWKkIQxLg2F3KKEBTf'

images:
  - 'gcr.io/$PROJECT_ID/automerch:latest'

options:
  machineType: 'E2_HIGHCPU_8'



